### ISSUE TITLE
AttributeError: type object 'object' has no attribute 'dtype'

### ISSUE THREAD

**Issue by Navid-visual** [yunshengtian/DGEMO#3]
I get this error when running the code. I really appreciate it if you help me. Please note that I used to run this code about a year ago with the same setting without any errors. 

Traceback (most recent call last):

  File "/local/Navid/DGEMO2/DGEMO/main.py", line 57, in <module>
    main()
  File "/local/Navid/DGEMO2/DGEMO/main.py", line 34, in main
    exporter = DataExport(optimizer, X_init, Y_init, args)
  File "/local/Navid/DGEMO2/DGEMO/visualization/data_export.py", line 69, in __init__
    self.export_approx_pareto = pd.DataFrame(columns=column_names) # export pareto approximation data
  File "/home/navid/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/navid/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 242, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/home/navid/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1221, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'

**Comment by yunshengtian** [comment]
I think this is due to the version of dependency packages. Please check if you installed the same version of dependencies (e.g. numpy, pandas) as what you have a year ago. Or simply use the version provided in environment.yml of our repo.

**Comment by yunshengtian** [comment]
Our repo has not been updated since 2020 so nothing really changed during the past year :)
